### ISSUE TITLE
Parsing issues

### ISSUE THREAD

**Issue by dfcreative** [MoOx/color-string#18]
There are some values which color-string is unable to parse:
* `hsla(10.0, 0%, 0%, 0)` - decimal point is ignored ([spec](http://dev.w3.org/csswg/css-color/#typedef-hue)).
* `hsla(-120, 0%, 0%, 0)` - negative hue value gets capped, whereas it needs to be rotated ([spec](http://www.w3.org/TR/css3-color/#hsl-color)).

Related issue: https://github.com/ben-eb/cssnano/issues/19#event-323079537

**Comment by MoOx** [comment]
PR are welcome :)

**Comment by Qix-** [comment]
Fix landed in 8627b8aeb1c3c46cef2d3956f9f524710f820abb.

Thanks @tusharpm for the PR!
